# Generated by Django 3.0.1 on 2020-01-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0002_auto_20200125_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyItems',
        ),
        migrations.DeleteModel(
            name='DailySubItems',
        ),
        migrations.DeleteModel(
            name='Vessels',
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
