# Generated by Django 3.0.1 on 2020-01-28 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0003_auto_20200128_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neworder.Items'),
        ),
        migrations.AlterField(
            model_name='ordersubitem',
            name='subitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neworder.SubItems'),
        ),
    ]
