# Generated by Django 3.0.1 on 2020-02-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0004_auto_20200128_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session',
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordersubitem',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordersubitem',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subitems',
            name='price',
            field=models.FloatField(),
        ),
    ]
