# Generated by Django 3.0.1 on 2020-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0006_order_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='subitems',
            field=models.ManyToManyField(blank=True, to='neworder.SubItems'),
        ),
    ]
