# Generated by Django 3.0.1 on 2020-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0007_auto_20200226_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hasGst',
            field=models.BooleanField(default=False),
        ),
    ]
